
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  h2:
    console:
      enabled: true

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;
    driver-class-name: org.h2.Driver
    username: sa
    password:

jwt:
  secret: keedeTravelyApplicationJwtSecretKeyPropertiesByLocal
  token-validity-in-seconds: 300
